use std::error::Error;

pub fn part_two(path: &str) -> Result<usize, Box<dyn Error>> {
    todo!()
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn day_twenty_four_part_two() -> Result<(), Box<dyn Error>> {
        assert_eq!(1, 1);
        Ok(())
    }
}
